package frc.team6223.robot.conf

const val LEFT_MOTOR_ENCODER_CHANNEL_A = 0;
const val LEFT_MOTOR_ENCODER_CHANNEL_B = 1;

const val RIGHT_MOTOR_ENCODER_CHANNEL_A = 2;
const val RIGHT_MOTOR_ENCODER_CHANNEL_B = 3;